name: Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          del requirements.txt

      - name: Build
        run: |
          pyinstaller -F --clean -y --dist ./ GUI.py
          
      - name: Clean Files
        run: |
          del __pycache__ -recurse
          del build -recurse
          del gui -recurse
          del utils -recurse
          del GUI.spec
          del GUI.py
          
      - name: Store generated file
        uses: actions/upload-artifact@v2
        with:
          name: Bili23-Downloader
          path: ./
