
name: Publish Windows Release

on: 
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Get Version Tag
      id: get_version
      run: |
        $tag = $(curl -s "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r '.[0].name')
        $version = ($tag -replace '^v|\.', '').ToCharArray() -join '.'
        Write-Output "tag=$tag" >> $env:GITHUB_OUTPUT
        Write-Output "version=$version" >> $env:GITHUB_OUTPUT

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RELEASE }}
        name: ${{ steps.get_version.outputs.tag }}
        body_path: CHANGELOG.md
        make_latest: true
        tag_name: ${{ steps.get_version.outputs.tag }}
        draft: false
        prerelease: false
        generate_release_notes: false
        discussion_category_name: announcements
