
name: Build Windows Release

on: 
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11 Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka requests wxPython qrcode[pil]==7.4.2

    - name: Get Version Tag
      id: get_version
      run: |
        $tag = $(curl -s "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r '.[0].name')
        $version = ($tag -replace '^v|\.', '').ToCharArray() -join '.'
        Write-Output "tag=$tag" >> $env:GITHUB_OUTPUT
        Write-Output "version=$version" >> $env:GITHUB_OUTPUT

    - name: Build with Nuitka
      run: |
        nuitka --standalone --nofollow-import-to=numpy,PIL --windows-console-mode=disable --windows-file-version=${{ steps.get_version.outputs.version }} --product-name="Bili23 Downloader" --company-name="Scott Sloan" --file-description="Bili23 Downloader" --copyright="Copyright (C) 2022-2025 Scott Sloan" --show-progress --mingw64 --assume-yes-for-downloads --output-dir=out src/GUI.py
    
    - name: Add License
      run: |
        Copy-Item ./LICENSE out/GUI.dist/

    - name: Upload Artifacts (no_ffmpeg)
      uses: actions/upload-artifact@v4
      with:
        name: Bili23_Downloader_v${{ steps.get_version.outputs.tag }}_win_x64_release.zip
        path: |
          out/GUI.dist
    
    - name: Upload Artifacts (with_ffmpeg)
      uses: actions/upload-artifact@v4
      with:
        name: Bili23_Downloader_v${{ steps.get_version.output.tag }}_win_x64_with_ffmpeg_release.zip
        path: |
          out/GUI.dist